// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Sibal

#ifndef _SIBAL_UI_H
#define _SIBAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Spinner3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Panel17;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel18;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label56;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label57;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_TabPage5;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label25;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label26;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label24;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label28;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label31;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label27;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Image3;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label35;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Keyboard1;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label48;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Label50;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_i03n_t_png);    // assets\i03n_t.png
LV_IMG_DECLARE(ui_img_i01d_t_png);    // assets\i01d_t.png
LV_IMG_DECLARE(ui_img_i01n_t_png);    // assets\i01n_t.png
LV_IMG_DECLARE(ui_img_i02d_t_png);    // assets\i02d_t.png
LV_IMG_DECLARE(ui_img_i02n_t_png);    // assets\i02n_t.png
LV_IMG_DECLARE(ui_img_i03d_t_png);    // assets\i03d_t.png
LV_IMG_DECLARE(ui_img_i04d_t_png);    // assets\i04d_t.png
LV_IMG_DECLARE(ui_img_i04n_t_png);    // assets\i04n_t.png
LV_IMG_DECLARE(ui_img_i09d_t_png);    // assets\i09d_t.png
LV_IMG_DECLARE(ui_img_i09n_t_png);    // assets\i09n_t.png
LV_IMG_DECLARE(ui_img_i10d_t_png);    // assets\i10d_t.png
LV_IMG_DECLARE(ui_img_i10n_t_png);    // assets\i10n_t.png
LV_IMG_DECLARE(ui_img_i11d_t_png);    // assets\i11d_t.png
LV_IMG_DECLARE(ui_img_i11n_t_png);    // assets\i11n_t.png
LV_IMG_DECLARE(ui_img_i13d_t_png);    // assets\i13d_t.png
LV_IMG_DECLARE(ui_img_i13n_t_png);    // assets\i13n_t.png
LV_IMG_DECLARE(ui_img_i50d_t_png);    // assets\i50d_t.png
LV_IMG_DECLARE(ui_img_i50n_t_png);    // assets\i50n_t.png
LV_IMG_DECLARE(ui_img_qr_png);    // assets\QR.png

LV_FONT_DECLARE(ui_font_NanumGothic);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
