// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Sibal

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void count_num1(lv_event_t * e);
void reset_num1(lv_event_t * e);
void reset_num2(lv_event_t * e);
void bar_toggle(lv_event_t * e);
void button_toggle(lv_event_t * e);
void save_restart(lv_event_t * e);
void Check_Update(lv_event_t * e);
void Update_Firmware(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
