// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Sibal

#include "ui.h"

void bar_toggle(lv_event_t * e)
{
	// Your code here
}

void button_toggle(lv_event_t * e)
{
	// Your code here
}

void saveBirthDay(lv_event_t * e)
{
	// Your code here
}

void count_num1(lv_event_t * e)
{
	// Your code here
}

void count_num2(lv_event_t * e)
{
	// Your code here
}

void save_restart(lv_event_t * e)
{
	// Your code here
}

void reset_num1(lv_event_t * e)
{
	// Your code here
}

void reset_num2(lv_event_t * e)
{
	// Your code here
}

void Check_Update(lv_event_t * e)
{
	// Your code here
}

void Update_Firmware(lv_event_t * e)
{
	// Your code here
}
